### ISSUE TITLE
Problem with Firefox 54.0

### ISSUE THREAD

**Issue by pgeorgiadis** [petea/sage#151]
It appears that after Firefox 54.0 version sage is not working properly.

The feeds are not showing in the sage sidebar. All other functionality (settings, etc) seems to be ok.

**Comment by Protestnik** [comment]
Same here, can confirm

**Comment by GussyFinkNottle** [comment]
Another confirmation. Perhaps more interesting: the paypal contribute link doesn't appear to work!

**Comment by petea** [comment]
Related Get Satisfaction topic:

https://getsatisfaction.com/sagerss/topics/firefox-54-0-64-bit-with-sage-1-5-4

**Comment by petea** [comment]
Newly added definition of "Cu" in placesOverlay.xul is causing a redefinition error on sidebar load.

https://hg.mozilla.org/mozilla-central/rev/8947d02cec5d

**Comment by inspector71** [comment]
Thanks for the fast action on this one Pete. How can we test it for you?

**Comment by petea** [comment]
@inspector71 should have a new release on AMO shortly.
